# Uncomment the next line to define a global platform for your project

# 官方仓库源
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '11.0'

inhibit_all_warnings!

use_frameworks!

def commonPods
  pod 'SwiftyUserDefaults' 
  
  pod 'YYKit', :git => 'https://github.com/CoderLouie/YYKit.git', :branch => 'swift'
  pod 'SwifterKnife', :git => 'https://github.com/CoderLouie/SwifterKnife.git', :branch => 'develop'
  pod 'SnapKit', :git => 'https://github.com/CoderLouie/SnapKit.git', :branch => 'my_source'
  pod 'lottie-ios'

end

target '${POD_NAME}_dev' do
  commonPods
end

target '${POD_NAME}_dis' do
  commonPods
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

# abstract_target 'abstract_pod' do  #这里的abstract_pod在实际targets中不存在，是虚拟
# 	pod 'SwiftyUserDefaults'
# 	pod 'Reusable'
# 	pod 'SnapKit'
# 	pod 'Then'
# 	pod 'SwifterSwift'
# 	pod 'Alamofire'

# 	target '${POD_NAME}_dev' do
# 	    pod 'Masonry'
# 	end

# 	target '${POD_NAME}_dis' do
# 	    pod 'SDWebImage'
# 	end
# end




 
